# Generated by Django 5.1.7 on 2025-03-23 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coridinator',
            name='role',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
