# Generated by Django 5.1.7 on 2025-03-23 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0002_coridinator_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
        migrations.AddField(
            model_name='student',
            name='academic_year',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='programme',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
