from django.urls import path
from . import views

urlpatterns = [
    path('view_group',
         views.view_group,
         name='view_group'),
    # Topic urls
    path('add_topic/<int:group_id>',
         views.add_topic,
         name='add_topic'),
    path('view_topic',
         views.view_topic,
         name='view_topic'),
    path('edit_topic',
         views.edit_topic,
         name='edit_topic'),
    path('delete_topic/<int:topic_id>',
         views.delete_topic,
         name='delete_topic'),
    # Presentation urls
    path('add_presentation/<int:group_id>',
         views.add_presentation,
         name='add_presentation'),
    path('view_presentation',
         views.view_presentation,
         name='view_presentation'),
    path('edit_presentation',
         views.edit_presentation,
         name='edit_presentation'),
    path('delete_presentation/<int:id>',
         views.delete_presentation,
         name='delete_presentation'),
    # Record URLS
    path('add_record/<int:group_id>',
         views.add_record,
         name='add_record'),
    path('view_record',
         views.view_record,
         name='view_record'),
    path('edit_record',
         views.edit_record,
         name='edit_record'),
    path('delete_record/<int:id>',
         views.delete_record,
         name='delete_record'),
    # Project URLS
    path('add_project/<int:group_id>',
         views.add_project,
         name='add_project'),
    path('view_project',
         views.view_project,
         name='view_project'),
    path('edit_project',
         views.edit_project,
         name='edit_project'),
    path('delete_project/<int:id>',
         views.delete_project,
         name='delete_project'),
]