# Generated by Django 5.1.7 on 2025-03-23 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(auto_now=True)),
                ('topic_submission_date', models.DateTimeField()),
                ('presentation_submission_date', models.DateTimeField()),
                ('record_submission_date', models.DateTimeField()),
                ('cordinator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='auth_module.coridinator')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='auth_module.student')),
            ],
        ),
    ]
