# Generated by Django 5.1.7 on 2025-03-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cordinator_module', '0002_studentgroup_project_submission_date_evaluation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgroup',
            name='presentation_submission_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='project_submission_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='record_submission_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='topic_submission_date',
            field=models.DateField(),
        ),
    ]
