# Generated by Django 5.1.7 on 2025-03-23 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0003_remove_student_address_student_academic_year_and_more'),
        ('cordinator_module', '0003_alter_studentgroup_presentation_submission_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentgroup',
            name='student',
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='student',
            field=models.ManyToManyField(to='auth_module.student'),
        ),
    ]
