# Generated by Django 5.1.7 on 2025-03-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cordinator_module', '0004_remove_studentgroup_student_studentgroup_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroup',
            name='is_presentation_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='is_project_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='is_topic_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
