# Generated by Django 5.1.7 on 2025-03-23 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cordinator_module', '0005_studentgroup_is_presentation_submitted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroup',
            name='is_record_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
