# Generated by Django 5.1.7 on 2025-04-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cordinator_module', '0006_studentgroup_is_record_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroup',
            name='assigned_faculty_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
