# Generated by Django 5.1.7 on 2025-04-02 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cordinator_module', '0007_studentgroup_assigned_faculty_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgroup',
            name='assigned_faculty_id',
            field=models.IntegerField(null=True),
        ),
    ]
