# Generated by Django 5.1.7 on 2025-04-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cordinator_module', '0008_alter_studentgroup_assigned_faculty_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroup',
            name='marks_obtained',
            field=models.IntegerField(null=True),
        ),
    ]
