# Generated by Django 5.1.7 on 2025-03-23 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cordinator_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('abstract', models.TextField()),
                ('submitted_on', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField()),
                ('remarks', models.TextField()),
                ('status', models.CharField(max_length=100)),
                ('student_group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cordinator_module.studentgroup')),
            ],
        ),
        migrations.CreateModel(
            name='RecordSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/record/files')),
                ('submitted_on', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField()),
                ('remarks', models.TextField()),
                ('status', models.CharField(max_length=100)),
                ('student_group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cordinator_module.studentgroup')),
                ('project_topic', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student_module.topicsubmission')),
            ],
        ),
        migrations.CreateModel(
            name='PresentationSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/presentation/files')),
                ('submitted_on', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField()),
                ('remarks', models.TextField()),
                ('status', models.CharField(max_length=100)),
                ('student_group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cordinator_module.studentgroup')),
                ('project_topic', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student_module.topicsubmission')),
            ],
        ),
    ]
