# Generated by Django 5.1.7 on 2025-03-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentationsubmission',
            name='submitted_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='presentationsubmission',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='recordsubmission',
            name='submitted_on',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='recordsubmission',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='topicsubmission',
            name='submitted_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='topicsubmission',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
