# Generated by Django 5.1.7 on 2025-03-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_module', '0002_alter_presentationsubmission_submitted_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentationsubmission',
            name='remarks',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='recordsubmission',
            name='remarks',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='topicsubmission',
            name='remarks',
            field=models.TextField(null=True),
        ),
    ]
