# Generated by Django 5.1.7 on 2025-04-01 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cordinator_module', '0006_studentgroup_is_record_submitted'),
        ('student_module', '0004_testtable'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/record/files')),
                ('submitted_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('remarks', models.TextField(null=True)),
                ('status', models.CharField(max_length=100)),
                ('project_topic', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student_module.topicsubmission')),
                ('student_group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cordinator_module.studentgroup')),
            ],
        ),
    ]
