# Generated by Django 5.2 on 2025-04-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_module', '0005_projectsubmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicsubmission',
            name='abstract',
        ),
        migrations.AddField(
            model_name='topicsubmission',
            name='file',
            field=models.FileField(null=True, upload_to='media/topic/files'),
        ),
    ]
