# Generated by Django 5.2 on 2025-04-20 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_module', '0006_remove_topicsubmission_abstract_topicsubmission_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestTable',
        ),
    ]
